protein_2_mRNA = {'A': ['GCU', 'GCC', 'GCA', 'GCG'], 
'C': ['UGU', 'UGC'], 
'E': ['GAA', 'GAG'], 
'D': ['GAU', 'GAC'], 
'G': ['GGC', 'GGA', 'GGG', 'GGU'], 
'F': ['UUU', 'UUC'], 
'I': ['AUU', 'AUC', 'AUA'], 
'STOP': ['UAA', 'UAG', 'UGA'], 
'K': ['AAA', 'AAG'], 
'M': ['AUG'], 
'L': ['CUU', 'CUC', 'UUA', 'CUA', 'UUG', 'CUG'], 
'N': ['AAU', 'AAC'], 
'Q': ['CAA', 'CAG'], 
'P': ['CCU', 'CCC', 'CCA', 'CCG'], 
'S': ['UCU', 'UCC', 'UCA', 'UCG', 'AGU', 'AGC'], 
'R': ['CGC', 'CGA', 'AGA', 'CGG', 'AGG', 'CGU'], 
'T': ['ACU', 'ACC', 'ACA', 'ACG'], 
'H': ['CAU', 'CAC'], 
'V': ['GUU', 'GUC', 'GUA', 'GUG'], 
'Y': ['UAU', 'UAC'], 
'W': ['UGG']}

mRNA_2_protein = {"UUU":"F", "UUC":"F", "UUA":"L", "UUG":"L",
       "UCU":"S", "UCC":"S", "UCA":"S", "UCG":"S",
       "UAU":"Y", "UAC":"Y", "UAA":"STOP", "UAG":"STOP",
       "UGU":"C", "UGC":"C", "UGA":"STOP", "UGG":"W",
       "CUU":"L", "CUC":"L", "CUA":"L", "CUG":"L",
       "CCU":"P", "CCC":"P", "CCA":"P", "CCG":"P",
       "CAU":"H", "CAC":"H", "CAA":"Q", "CAG":"Q",
       "CGU":"R", "CGC":"R", "CGA":"R", "CGG":"R",
       "AUU":"I", "AUC":"I", "AUA":"I", "AUG":"M",
       "ACU":"T", "ACC":"T", "ACA":"T", "ACG":"T",
       "AAU":"N", "AAC":"N", "AAA":"K", "AAG":"K",
       "AGU":"S", "AGC":"S", "AGA":"R", "AGG":"R",
       "GUU":"V", "GUC":"V", "GUA":"V", "GUG":"V",
       "GCU":"A", "GCC":"A", "GCA":"A", "GCG":"A",
       "GAU":"D", "GAC":"D", "GAA":"E", "GAG":"E",
       "GGU":"G", "GGC":"G", "GGA":"G", "GGG":"G"}