def main():
    filename = "./data/rosalind_dna.txt"
    data = fasta_read(filename)
    dna = 'GTCGTCAGTACATGTGCACATCTGGTGCAGGAGCACGGTACCAGTAATGAGACCAAGTAGAGAAAACTCGCTTTGGGCCTAAGCTGCGTTCATTATTACTGCATGATGCTAACTCATGCCGAATCCTACGTCGTATCGTAGTTACGCATCCCCGGTGTATTGCCGTTGCCGGTGTAGTGTGTGTTCGAAGAAACTAGCCATTGATCGACTATTGAAAGCTGGTTTCGGTATTTATTATCACAAACCGTGTGTCTGTGTCATTCCGCAAGGGTACGAAATAATGGGACAAGCGAATTAGAGCCGGTTGAGTACTAACTCAACTACTAACGACTACCCTATCTTAGTCAGCGACATGTGCTTAGATGTACCTATCCCAACCGCCCTGACTAGAACCGCTTGTCCTTTAACGACTAGAAGTGCGCAGAAGGCTATGGTTATGCACGCGGCGTTGTAGAACACCTGCTCTTAGAGTGGTATACAGTAACCAGAAGCCTTATTAGCGGTCGTGTCTATTTGTAATATTTTTCCGGCACCGTATGTGTTCGGTAACTCAGCTGCATTCGCGTGTTAATAGACAGAACCTATGAACGACTATCTTGGCGGCATCGTAGGGAAACGCGTTTGTTATGAAATGACGTTGGAGCCAGAGCGTGGACCCAACATCGATGTGGGCTAAGGGGTGGCTACGACGTAGCCGCGGCCTTTTGGGAACGGAGTGCGCTTCGGGCGAATAACGTCCTGCCAAGGAAACGTAGTATAGCTAGGCGCTGTATGAAAGCTAAACCGCTTTAACCATTGCTACAGTCCCACGCAGTCGGCGGCTCTCGCCGAAATTCTTCCCCTAGCCTATATGCAGAGGACCCTAGTGTCGCACTAGGGAACGCCATAATCCGAGACTTTAGTGTTGCCCAGTCAGCAATGCTACGTGGTTTCGATCGAGGGTTGATGGAAGCAGAGATAAGTGAGGCTATATGAGGG'
    count = {}
    count['A'] = 0
    count['C'] = 0
    count['G'] = 0
    count['T'] = 0

    for i in dna:
        count[i] += 1

    print count['A'], count['C'], count['G'], count['T']


if __name__ == '__main__':
    main()
