import gc

def build_rank(T):
	rank_last_col = []
	rank = {}
	rank['A'] = 0
	rank['C'] = 0
	rank['G'] = 0
	rank['T'] = 0

	for i in T:
		if i == '$':
			rank_last_col.append([i,-1])
			continue

		rank[i] += 1
		rank_last_col.append([i, rank[i]])

	return rank_last_col, rank

def LastToFirst(T, i):
	first = ''.join(sorted(T))
	rank_last_col, counts = build_rank(T)
	del T
	gc.collect()

	c = rank_last_col[i]

	if c[0] == 'A':
		ans = c[1]

	if c[0] == 'C':
		ans = counts['A'] + c[1]

	if c[0] == 'G':
		ans = counts['A'] + counts['C'] + c[1]		

	if c[0] == 'T':
		ans = counts['A'] + counts['C'] + counts['G'] + c[1]

	return ans

def main():
	# T = "T$GACCA"
	T = "CACTGCACTAAATGTCGAACAAGCGTTAATTAGCTTGGTCATCGTTACCGTTAACTAGCACTATGCCTTATTGATCTGTTACCGACCGGGTCGTTGTTGTATGATGGATGCACTTCTGCTCGACCGGGATTGGGGTCGCGGAGAAATTGTCGCTTCTCCTCGACCACTACGTAGACAGGAGGTAAGTGTAGGGGTAAGTGCGTCCAACAGGCGTCTCCCGATGATGTCGAATCTAGGCCCCCCGGGCTCATACTGCTCTACTCCGCCCACTCAACTACTGAGAACACGTAAAGCCTCTGGGGCGAACCTGGGTGCTAAACTAGATATTGTAACAGTCAGTACGGCCGGCCGTGCTGACGGGCAAACTAATGAATCCGGCGCTTTAAATGGCATTGTGGCTAGATCCACTTGTGGACGAATCACAGTGAGAAATACATGCCGTTCCACTGTTTCGCTCCACGAGACCGGGCGAGCCTCATTACACGGTGTAAAACCATTTTTTGTTTCGCTCAGAGACCAGGCGGGCAAGAAAAACTCATCTAATGTTAGATCGGTTAGCTTAGAATAAGCTCGCTTCAGCTCTTGGAGACATTACATAAGTTTTCTTTGTTTCTCGCATGCTCGTCAGTTTATCAGCGAACCAGCAGTTACTCAACTCGATCAGTTGACGGAACCAAACTAGTGTATATAAGCGTTAGCCCGCGACGAATTTAGGCCACTAGGTCTCACGAAACAATATGAGTACGCGTGAGGAGCCGCTGCTCCAATGTTATTGAACTTGCAGACAGCTTGCGGCTAAAGGCAGTCAATGATTAGGTCCC$"
	i = 794

	print LastToFirst(T, i)

if __name__ == '__main__':
	main()