import pdb

# pdb.set_trace()
def find_min(a,b,c):
    if c <= a and c <= b:
        return c, 2

    elif b <= a and b <= c:
        return b, 1 

    elif a <= b and a <= c:
        return a, 0

def EditDistance(S, T):
    m = len(S)
    n = len(T)
    gap = 1
    cost = 0

    align1 = ""
    align2 = ""

    # A = [[0]*(n+1)]*(m+1)
    A = []
    ptr = [[-1]*n for i in range(m)]

    for i in range(m+1):
        temp = [gap*i]
        temp += [0]*n
        A.append(temp)

    for j in range(n+1):
        A[0][j] = gap*j

    for i in range(1, m+1):
        for j in range(1, n+1):
            if S[i-1] != T[j-1]:
                cost = 1
            else:
                cost = 0
            A[i][j], dirn = find_min(cost+A[i-1][j-1], gap+A[i-1][j], gap+A[i][j-1])

            ptr[i-1][j-1] = dirn

    i, j = m-1, n-1

    while i >= 0 and j >= 0:
        val = ptr[i][j]
        # print val 
        if val == 0:
            align1 += S[i]
            align2 += T[j]
            i -= 1
            j -= 1
        elif val == 1:
            align1 += S[i]
            align2 += "-"
            i -= 1
            
        elif val == 2:
            align1 += "-"
            align2 += T[j]
            j -= 1

    while i >= 0:
        align1 += S[i]
        align2 += "-"
        i -= 1

    while j >= 0:
        align1 += "-"
        align2 += T[j]
        j -= 1

    return A[m][n], align1[::-1], align2[::-1]

def main():
    # S = "PRETTY"
    # T = "PRTTEIN"
    S = "MFYTMGMRSNRKPQVRLGVHDWNMIHCYEPANTWHEPNVDNQNARYKLREMVVVAPNAEI\
KHAKKRKNTADIWIVHPWQMNAIFEWIEHAATHSYQSGPDRWLVCLDFTQRPTGSKVMHP\
VIVQSFTHFICKTYYIQQEHKPCLMYMNLRICGHWIYSDVWYAKRMAHTCSAYPWTGHFF\
AMVCFQVVDVCKTADVLFHLPCTDYSRPEYWRPPRFKVEYPERDCEKHGPLKLDQNKFCS\
KSRMMWQQPYETHSPSVFYIPMAQFSYMQFTSKHVWYNMVMKTKWGTGPHRHVYEQYCMH\
TKVSRTRFYMDSWHQRVTDLNYEDLAMAAHNPGAHTHYNWSGASGLFPANCTVTCAEIQI\
QPTYDAPIARMQTATPCFKRHGAWHWQRRAWWFWQCAHDFDDQPKRKQQNYHSYVDCLIS\
AAGRFVQNNMCWMEMRHCLKRTDSVIKPRMYVKLRWWIWHDLHEQVVGGMTIYAYRLCSD\
LTKQTKWTDLFEEIDHWVTRMMHPLDWFGITALGTMHKVDYSYAYDHILSRSFLEVPFYV\
QQKADPISSIHGIRNCQCRLRWLLLVEDFIVHIYNDVDAYGDFKVTSMPGQYYLYWVYIR\
MDKAERWVDLHYGWNRIGCTMCRFYMQGDMQKTTMPYAKAKPSTESMYLSIVYHETHMER\
AFRHQNALRGSVHRFMRCMVANFYEKRKYDQAKSFVEADIFNRSVADDWTWHGAPTHQNA\
ETNPFWHCSFYGTFEVMTDHDELKFVGHFMMITRLGFMRLYKSSGMMKLVDLTECQIPPQ\
VTAMWKQNSCMFNPCFTITTNRFQQWWHVCIFYTYWVGYGMEWRGSMINMTQVNEYHMAH\
YLQDQNAGDATRSVIPGTEMDHLGPERRAQEDQEQYPTTGEREVRHKEQWAHFQPDF"

    T = "MFYTWGMRFNRKPQVRLGVLDWNMIYCYEAEFCANTWHEKNVDNQTDRRLRWMVVVAPNA\
EIKHAKIIEGRKNTADIWIVHPAQMNACFEWIEHAATHSYQSGPDRWLVCLDFTQRFTGV\
KVMHPVIVFICKTYDIWQGNMRATWADKPCLMYKNLRQYNWIYSAKRMAHWTGHFFAMVC\
FQVADVTADVSGHLPCTMYSRPEPERPPRFKVQYPERDCEKHGPQKLDQLRAKFREAKGS\
CSKLRQMWQQKYETHSPIVYIPMAQFSYMQFTSKHVLITRLWYNQVMKTKWETGPHRHVY\
EIHVQYCIHHGQDVGEDKVSRTRFYNPDSPSAHDRVQDPVIMPCFDLNYEEQQPDATGEA\
SAAHNPGASGASGLQPANCTPIARMQTATPCFGFWFVFKRHGAIEWQRRAWWFWQCAHDP\
DDQPKRKRQPYHSYSDCLISAAGRFVQYNMCWMELKRTDSVIKPRMYMLNQYKLCWWIII\
FHVHGGMTIYAYRLCSDLTKQTKWTDLIDHWVTPMAHPLDWFGITAHGMMHKWCKLWLPL\
SHPSHIMNILPFYVQQRIDPISSIHRNCQCMTAPEHIYNDVDAYGSFHVTSMPMQFDCED\
IVLFLRMRDSGLGHDKAQHQTTMPVCHYGWKRIGCMMCRFYMQTTMKAKPSTESSYLSIE\
YHETQMENFVAFNSDQYKSDVHRFMRCMVANFYEKWEEHHYRKLDFHTSHRAKSFVEADH\
FNRSVAYTSWTWHTETNPFKIEGELQFIGHFMNLHFRTRLRAMRRLPKYLIMMKLVDLTE\
CAIPPQVICYTLCFFRHLSQITTNRFQQVDIESQIFMWHVCIFYVYAGVGYGMVWRGSMF\
TRNMTQPSWPEYHWAHYLQDQNAPGMDHLGPEKRAQTEDQENSYYPTTDEREVWVLEKQP\
DM"

    dist, align1, align2 = EditDistance(S, T)
    print dist
    print align1 
    print align2


if __name__ == '__main__':
    main()