def EditDistance(S, T):
    m = len(S)
    n = len(T)
    gap = 1
    cost = 0

    align1 = ""
    align2 = ""

    A = []
    ptr = [[] for i in range(m)]

    for i in range(m+1):
        temp = [(gap*i, 1)]
        temp += [(0, 0)]*n
        A.append(temp)

    for j in range(n+1):
        A[0][j] = (gap*j, 1)

    # count = 1

    for i in range(1, m+1):
        for j in range(1, n+1):
            if S[i-1] != T[j-1]:
                cost = 1
            else:
                cost = 0
            min_item = min(cost+A[i-1][j-1][0], gap+A[i-1][j][0], gap+A[i][j-1][0])
            # A[i][j] = min_item
            count = A[i][j][1]
            # ptr[i-1].append([])

            if min_item == cost+A[i-1][j-1][0]:
                # A[i-1][j-1].append(0)
                count += A[i-1][j-1][1]

            if min_item == gap+A[i-1][j][0]:
                # ptr[i-1][j-1].append(1)
                count += A[i-1][j][1]

            if min_item == gap+A[i][j-1][0]:
                # ptr[i-1][j-1].append(2)
                count += A[i][j-1][1]

            A[i][j] = (min_item, count)


    i, j = m-1, n-1
    # write a recursive function to backtrace the alignment, specifically DFS
    # print A

    return A[m][n][1]#, align1[::-1], align2[::-1]

def main():
    S = "GLFIAHDPVRIYAFYTVQCMQSFEFIRSNEAAPHAFPVGFPQYPTGVDPHERDGQMKCFF\
NDTLCGPDDCSKSGEIINPLVRKGDFNKRWHAIRRFTAARAPQFVDMDINYWTPTLVTPI\
PNKFAFWYFWHAYHTYMERWWDQKEHHRKWFKKRKWCHGQRLMWTRPCPLLWMRLIEQGL\
QDPFYIGSFVHMAQTVIDSNCHPMVHFIMVGGCLDICAQWLEYMTLVKEMDWHICRYVFP\
LTDNFIVQCLKWHRFCAVHVAMPMLGQHGAKTSVQTGCFDEKYMVCQGSECTQDHWYAAD\
TRDEACTMCKCVWMLRRVGTEQVYTLGMIPGFAFMDYQEGGMFGKILCWFPGFWVQGHMP\
ERSRSDEYKNMLEHPQQAEPGKCFRCVWKEWEWRFGQCPDRQMASNNGKSPVENRTTIYI\
IFLQRVIGHIWLHTFNKACVYMGNFVLPCANWKEDTRPDLQAGSLKIIMIHGVCPWFPIC\
SMNDWSGYYRTRKIDYSRSRMQELTFKIFVYTRVWSMLWTMRGDGGCVPCNKATRPKLCC\
HSEDFQSSFESWGIFEKKHQWARVKSSLLSFDGKQPCISKLTTVHGRFHVAAVIPQVWKM\
VYVQGWNAMEFSDIMHEPSMDPQWPCYTDCIFIPKDPGAQHSEVAFISMTELKSFAVDMF\
WHVGDYNRRRSDINFEGMPDKLSMDHHWKMIQDRDCRIAFFFYSKHYDPFTPMFFITTDR\
SMQFNMRDTTQHQEITQYGSATWLIVKLWIMIFMFMRPIVSCYENYTEQPLYLYV"

    T = "GLRIAPGPKHDPDRIYAFYAMRHLIVQSFETNGIRSNEAAPLSFPVGFPQYITGHHAEED\
DPHERDGQMAGPDDCSKSGFVRKGYFNKRWHAIRRAMHCIPGMDINYPCPVKTPALVTPI\
PYFWHAYGNVQTYMETKRKPCHGQRLMWTRPCMFHWVHEQGLMQQGGWKHQKDSNCFPMK\
HFIMVGGCLDICAQWHICWYVFICLTLNFIVQCLKWHRRKNQADHWSNLTHGANHFHQAH\
DEKYMVCVSECRPGHMEMQDHTQAADTRDEAMLFKQEWFPTMCKCVWRTCDGFAFGMIPG\
FAFMDYQQDVINHWHAKILCWFPGQWVSAGHMPERSRSDEYKNMLEHPCWWLGRCVWKEW\
EWRFGQCPDRQVSQNNGKSHFPQTIYIIFLQRVIGHILLHTFNKCCVYMGNFEDTRPDLQ\
QYGWALYKAGSKIAMIHGVCPWFPYPMGWIDWSGYYRTRKIDYSRIRMQELMFKIFVYTR\
VWVMLWTMRGDGGCVPENKATRPKLCCHQSTSFESAGWARVYECVNTAICFHCISKLTPV\
HGMFHVAAVIPQVWKMVYVQWNFKCQPMEFAMHEPWMDPQWQCKDPGAQHSFNNMFIEMT\
ELCSFAKDYFNHVGDYGEGMAAKLIPMDHHWPLTMRMMMIQDRDCRILYVKFFHFYSRHY\
DPFTPMFFITTDRSMQFNMRDVTQHQEITQSATLLIVKLWIMIFMFMRPEISAYENYHCK\
MQHQPLYLYV"

    ptr = EditDistance(S, T)
    print ptr%134217727


if __name__ == '__main__':
    main()