

def EditDistance(S, T):
    m = len(S)
    n = len(T)
    gap = -1
    score = 1

    align1 = ""
    align2 = ""

    A = []
    ptr = [[-1]*n for i in range(m)]

    for i in range(m+1):
        temp = [gap*i]
        temp += [0]*n
        A.append(temp)

    for j in range(n+1):
        A[0][j] = gap*j

    for i in range(1, m+1):
        for j in range(1, n+1):
            if S[i-1] != T[j-1]:
                score = -3
            else:
                score = 1
            A[i][j] = max(score+A[i-1][j-1], gap+A[i-1][j], gap+A[i][j-1])

            if A[i][j] == score+A[i-1][j-1]:
                ptr[i-1][j-1] = 0

            elif A[i][j] == gap+A[i-1][j]:
                ptr[i-1][j-1] = 1

            elif A[i][j] == gap+A[i][j-1]:
                ptr[i-1][j-1] = 2

    i, j = m-1, n-1
    gapcnt = 0

    while i >= 0 and j >= 0:
        
        val = ptr[i][j]
        # print val 
        if val == 0:
            align1 += S[i]
            align2 += T[j]
            i -= 1
            j -= 1
        elif val == 1:
            align1 += S[i]
            align2 += "-"
            gapcnt += 1
            i -= 1
            
        elif val == 2:
            align1 += "-"
            align2 += T[j]
            gapcnt += 1

            j -= 1

    while i >= 0:
        align1 += S[i]
        align2 += "-"
        gapcnt += 1        
        i -= 1

    while j >= 0:
        align1 += "-"
        align2 += T[j]
        gapcnt += 1
        j -= 1

    return gapcnt 

def main():
    S = "AGGTCGTGCGCATCCCCCTGTATTTGCGTGGTCCAATTCAAGTCCCCAGCGCCCGGTATG\
TGCCCGTGTTCCCTTGGGGAAAGTAAGATAGGACTTGGAATGCAGCTAGTCGTGTGTTTA\
CTGTCCCATCTAGCAAGATGGTGCGCCTCCGGGACAAATTTTTTCTCAAAAGCCATGTTT\
TGAAGCAGTATTTTCCCTGGAGTTTGGTCTTTTTTCTTTTGCTACGTTGGTCAAGTATAG\
CACCCAATAGAGATTAGATAATCTTGCAATAGCCCCTCGGGGGCCTCGAAGAGAGTATCA\
ATGTGCTATAAATGCCGCTGCTAGAGGCACACCAATCGATTCCTTCCTCGGATCCAAGAC\
TAGCTTGTGTCGGACTGTTATATGTGTACTGTCCCCACTTATTTGACATATTACGGCCGT\
CCACGCGTGGACAAAATAATGTTACATTATAGGTTAATTAGTTTGATACATCCAGACCTG\
AAACACCCAGCCTTCGCAGAGCCACTCACTGCTGTCGCCATCTCACTTTTAATCCTCAAT\
CTACAACAAACCTCTTCAATCCTACATCAGTACTGTTTAGTTTGCCTTTACATCCAGAGT\
CACGACCTGCTAAATACATCGGCAACTATAGGTTGTCGGTGCTATGATTGTCTGACACAG\
CGTACCCCCGACTTGCGCAGACCACCCGCCCTTGTGTATGTGCAAACTTGCATGGTCATT\
AGCGTATGGCGGTATTCCGATAGGCTCGGCTGGTGGTTATGGCTATAACGGATGCCACTG\
TCTCCGGAACACATTTAGCAATTTTCGTCGAGATTATCGCGTGCTCGGTCAGAACGCTAA\
AAAAGAGCGGGCGAACGCCGTCGGAAGGGAGGTCAACGTCCACAGCAACGGCTAGGGACC\
CCCCTTGCGGAGATGACACAGGACATCTCAACTCGTACCGGGGACGATTCTTGCGAGGGG\
AAGATCATTAAGGCACCTGCATCGGATAAGTTTACCCCCAGGTGATATACTTCGAGTCCA\
CGCAGGTAGGCTGCGGCTCGTCTCTAAGCAAACCCGTGGAAAGTGTCGGTAGATCTTGGA\
AGGTCGATTGGAGCCCTACGGGAACTTCTGTTTTTATGTGCGCCGTTCTCTACCGACTGC\
ATCCTTCCGTTTATTGGCTGGAAGGTCTGAGCGGGACACGTCTGGAGCCAGAGGCGTCAA\
ACGAAAGGTGAATCCCCATGTCTAGTACACAAGAGACTGATAGCGATCCGGTCGGCTCTC\
ACGCAGTACAGTAAGTGATCCGTGTCTCCGCCCGGGTGCCGACCTTGTGGAACGGGGAGA\
TATCTGTTACTGGCGTCTATTGAAGAAGGGGTGCGGTGCGAACCGAGGATTCCTGTCAGC\
AGAGCTTGCATACCGGGAGCTGCGAATGATCCGGGCAGGGGATATGGGCCTAAGCAAGGT\
ATCTGTAGTTCCGCTTTAGTGGAAATCTGATGGCTTCCGAAGGTTTTAGGATAAATTAGG\
TGGTTCAGGTTGTCCGAGGGGCTCCAGAATCAACTCCTACGGTTTCAATAATTGCACAGT\
AGGTGCGGGTAAGAATTGAGATTTCGTAGGAGCTAGCATATCATGGGTGTCCAGGATACT\
TAGGCCCACCAAACTCTCCCGACTAGTTGCCCCTTTGATGAAGTCCCCCAGGGTGCTTGG\
ACTTGGGACTAAGGCAACGAGGAGGGCTCCATGCCAATCGCACTTCCAAAGGCTATCTTC\
GGATGAAGTAGATACCGTACCTCAACCTTCGCAGCTTCCGCTACTCACTCGAATGATAAT\
TCCCGCGTGCACTCATAATCTCGTGATGAGAGGGCAGCGACAACGACGAACAAGGGCGAC\
GTCAATAGGGCTGCTGCTAGGACTCTAGAGCTTGATACAAAATTTAGTTCTGGGGCCATT\
GTGGGACCCCGAGATAGTGGGCTTTTACCATGCACTAGCTGTATCACGTCCTATCTGGGA\
GCACTGATTCGTTCGATAACTCGGTTTTAGGCATAGTTGATCAGAGTCTGTGGGGAAGGG\
GTTCACCCTGGGAATGAGCTGCGCTCGGGGGCTTCTATGCTTGAAGTTATAACGGAAATC\
CCTTGAGACGGAACCGACAATCTTGCGAGGGTTCTAATACAACTTAAGAGACCGTTTCTT\
TATTCGTGGCTATTTATAAAGTATGGGGATTAGATCGTACTGTGACGTTAAAAACCTATA\
TCAAGTGATACTGACGTAGCCTACGGCAGCTTCCTAGCAGAGAGCCTATCTTGACCCAGG\
GATGGAACGGAGTCTAGGGTGACGGTGTCATTGGTTCAGCAGCAAAACTAAGCATGCACG\
GCTGGTGAGACATCGTGCACTGTTAGTATTAGGGATGGGATGGAAGGGCCTACCGTTACT\
TGTGACCTAATAGGCTGATCTTTGTTAGCGAACGCTAGGGTCAGCCCGTGCATCCTATCG\
CCACGAAAGAAGGGGGGACTTGGACCTATGATAAAGTCACGAGCAACTACTTAGTTCGCC\
CTTGTTAACATACCTGCTTTGGCCGACCACTTATCCCAGCACGCAAGTAGGTCAATTATA\
GCCTTATAAAAGGCGTCGCGCGTGGCAGCGTGGCCCCTTCGAAGGCGACGTACGAGTAGC\
CCGGAGAGCCCTGCCATTTCCGTAAGTTAGATTACGCTGTGATCAACATTCAGGCTCTCC\
CTCGCTTAAGGAACCGCACACCCCGCGAACACCAACTCAAAATTGTTACCACCGCGAGGA\
CTCTAAGGAGCCGCATCTCATCAGGTGTTGACATCCTGTCAAAGTCAAAGTCTCGGCAGA\
ATGCTAGACAGTGGTGCAAGCGGTCAAAGGCGCCACGCTTTATCGCTAATAAACGTCTCC\
GCTGAGATAAACGAGGCTTAGCAACCGTATACTAGCGTTTCTACTTAGTCGTCCCTCATG\
GACATCTGGCGGTAGCACCAAGGTGCCACTGGTCTGTGCTGACTGATTTTCGTCGCGGAG\
CACGGGTAACAACCGGTGGCGGCGATGGTCATGGCCGGAACATCTTCTGGCAAATAACCG\
ACTCATAAGTCGTGGCGGATCCGCTGCATTCGAATCCCGTTGTACCGGTAAGTCGCGGCT\
ACACCCTAGGTAGGGAATTTATGGAAGGTTACGGGATCAATAGCCTACGCTCAGCATGTA\
GGCAGTCCAGGCCCTTACACGCCATTATCATATCGAAACTGCTTCCTAATCAAATCCCAG\
AGCTTTATTATGTTATTATAGGGGAAGCCCCCTGGACCGAGATATGCGCCGATATCTGCA\
AACAAGAAGGAGACATCTGGTCGGACACGGGATTGCGGAGTATGGAGGCTGCTGAAATAT\
AACACCCTAGGCAATGACAGGTACAAGTTCTTTTCAAACTTTACCTAGCTTGTCATAAAG\
ACTATACTTTTCAGGTGAGCAGCCAATAGCGCCCAAGTGGCCCAGGTGGTCTAACATGTT\
TACTGGATCGAACCCACACATGGAGAGGGAACCACCTTGTCGAGCCTAAAGTTGTGAGCT\
GTCAGTATAAGAAGCATAGTGCAATGATTTGGCGACGTTAAAAAGCCCTCCATGGGATCT\
CCGTAGTCCCAAATGGCTCGTCATGTTAGAAATGCCACAGCAGATCAACTAGTACAATTG\
TTGCCCGCATTTCAGTGCAAGCGCCAGCGTGTACACTATGACCGATACAGACAATGTTGA\
ACACGGCAGTCCTCTAGCGGTAGATAACGAGCTGCGCCACTCCATTCTGGTGTGACTCAG\
TCTCTTCGGTTGCCCTTGGAAATGACCCAGCGTTGACTTGCCAAGCCTGGACTGAGCCAG\
CAATGATCATAGAATTCGGGCCATAGCGTTTATTTTGGTCCTGCTTCCCAAGTAGTTCGC\
AGTGTTCTCAGCCTGCGGAAGGTCAGGCAAGGCGCTGTGTTCGCCGGGGTACCTTATTCG\
CCATCTATTACCTCGGACAGTTGAGTACGGCTCAGTGACCTTCCAGGGATATTCGGAAAG\
AACCCTATACACTATCACAACTGCGTTGCTCTGCGGTGACCTAGTGCTACTCCGTTGTGA\
GGAAAACGGTGAGCAAATTGCAATATGAACGTGAAATAGCGCATCGGGTCGTGGAGAACA\
TGGGAACATTTAGGTTCCCGTTCACGCGTGCTCAAAGGCGTCATATGTCACTGATCATCG\
GGCAACGCACCATCTCGGTCGTCGATCTACGAGTCCAGCTGCAGCTATTCGGGGCTCGTC\
ATCGCGCGCGCAATACAGACCCGGGTACTACCCTACTGGCCAACTTATAATAGCAGCAAA\
TAGCGCGGTAGAAGAGATGCATTGCTAGCGAAATCGAGACTCCTCACGAACGAACCCGTC\
AACGGAACCCACGGTAAGTACGCATCGCGTTCCAAAGTTCCTGGTCTGTGTGGACTCTGG\
ATGACCTCCTCTCGCGGAGAACACTGCATGACTCGAGAATACCTATAGCAACGAGACCAT\
GGCTTTCACACCTGGCGGCTCCCTCTCCAGACTCTCAAGTAAACGATACATTTATGACGG\
ATAGCAGAAAAGATTAACGTGAGATCATCGGATCGCATACTAGCACTCCTCCGAAGGAGC\
TCTTTCGAAAGACCCTCTTATCCACGCGCTCTTCATTGGTCTTCGCTACGAGAGTTGAAT\
ACGCCATCGGCGCTGTTTTAATTAGATATCCCCTTAGTAGTTATCAAAATGTGCGGCCAG\
GGGCATAAAGTGGCGGAC"
    T = "CGATCTGGAATACCGACTACCCCGGGCTGCGCTCATGTCTGCCGTTTACAGAATTGGGGC\
GACTTCGGATTTGATTACCAGGTTATCCACATCTCTACAGCCGAAGTCGTGGCCTGTTTG\
GTGCCATCATCAAGGGTCGCAATAAGTAGCCTGCTCAAACATAATCGCTATGTAACACTC\
GAACAGTAAATATTGGCCCTACCCGGATATATGCATTGATAAGAACGTTACCCAGGGCTT\
ACGAAATCTATATACGGGGACTGCGCGTAGGCATAATGGCGTACGGACTGCAAACTGCTA\
CGCTAGTTCGAGGATTGGGAGGGCCATTTCACAGATTGTGCTTTTCAGCACGCGACGATG\
ATTCCACGCCTACAAATTGTCGTCTCGCGGCTCATGTAATTCGACAACTTAGTCGGGACT\
TGCGGCTTCGGTTGGTGTCTTCTTTAGGGGACCACAGACCCATTGTCCCCCTGCACTAAG\
TAGATAAATTTAGGCTACCTTGTACAATGTCCTTAAGTATTGGTCGTTCTTCATTTTGTA\
AGCCCACGGCACTTGAGTGGTCGTGTCGGTTGCCTACTTGGCTACCCAGGTGAGCGCGTA\
GGTCCTGTTTACCTCCTACTGTTGAAGCCCTACTGTACTTCCCGTCACCCAGAAGCTTCT\
GATTAGAGTGTCATTTCAGTTGACTGGAAGCAATTTCAAAAAGTCCACCCGTTTAGTTGT\
CTCTCGCTGTGAGGATGGTTTCCTTTGTGGAAGGTAAGAGACCGTGGGATTACGAGGATA\
GAGGATATTCGACTGCCTAGTAATTTCAGCCGCGGATGTTAAAACACAGACATTTTCATC\
AAAGGGTCCGTTCCAGGGATCGAGTGCTAAAAATAACAAGAAGCGGCGGGACGAGCTGGC\
TACACTAAGGACCGGGCGAGCGGATGTCCTGGTCGTGGGCGGAAGCAGCGACTGTGCCAC\
ATTTAGTGAGTATGGCTCTCTGACACTTGCGACTATCCTACGCCCTGATTGGATCAGAAC\
CGGTGTGGTGACCATAGAATTCAATCTTATATGGGTAACTCAGTCTAATGGCTTTGAACA\
GTACCAGTGCTCTGTCCATGAAGTGTCTAACAGCACCGTCCAAAGTTTGGGCTTGACAAA\
TGACTATAAGCTCCTAATCGGGTAATGCGAGAGACTGTCGCGGTCCTACTCAGGAGCTTA\
CGGTCTGGGGACTATAGAACCAACAATTAGCGCCGAGGACGAAGGTGATTGCGCGAAACT\
GGGCTTAAATTTCGTGCGCCAACCGGCGTTGAGGCTGGGATCATTCATTTTAATTCGAAA\
TTACCGGGTTTTCTTGTTATATCCACACAGTAACAAGGGTCCGGTCCGGAAACGAGTATA\
TTGTCCACTAGTCACCGTATCGTGGACAGCTTTCAGCCCCATTCAGGCCGTAACGCTTTC\
ACCAAGGGTGTAGACACCTCGTGTCACGTATTCGGGGATTTAGCCTAACGCTACCTCAGA\
TGTACCCGACCTAATGTACGACCTATCCCAAATAGTGTGTCCCACCGAATCCATCTGTAG\
AGGCAGTGCAAATACGATTGGTAGACATGCGTACTCGGGCCGCAATAGGAAAGCTTGTCT\
ATAGTGACAATAATGTTCGGCCCATATCCTGCAATGGCGGTATATTCGGGATGAGAAAAC\
CTAGTATTTAGATCCTCAAGGGCTTGGTCCCGCAGTCCCGGCTGAAAAACGTCGGCCCAG\
CTAGGAACAGTTTTCCAGGAGTACATTTATCCCTGGCAGACAAATTGGCGCCCATTCATC\
CGGTGCCGCGGGAATCAGCGTTACCAGCAATCTACGTACTTAAACGAAAGAAGTGGATTC\
CGATCGCATATTGCGCGCGGAGGTTTCGTTGCCATCGGTGGTAGTTCTCATCCTGTCTGG\
AACCGTCTACATAGCCAAGCTCTCGGTAAGCAGCGCGTGTCAACCCGTTGTTATCTCGTG\
GCATATCGATTTCGCATGTTCACAAAGACGTCGCACACCATCGTTTTTGGGTGGGATACC\
CTCCACAGGTACGAGTTAGAGAAGCACTCTAAGCGGTCTACACGAGCGCTTGTACGTGTA\
CGGGAGTAACCACGATGTCCAACGCGAAAGGAGAGGCCCTCGGGCTCGGCAGCGCGCGCT\
GATAAAGATTTAGTAGGGGATCTTAAGCGCTAGGCCGAAAGTCCCGGATCCACTGATCCG\
GGATTATGTTCAGACACACTTCGTCAGCGAACGTGATTCCTACAGGGGTATCGGATCAGA\
ATGCCACCCCGTTACTCCAAGAACATCCCAATGAGGGCTACCTGTTGAACTCGACAGATA\
CCTGGCAGGCCCGAGAGAGTCTCTGTAAGACGCCAGAATGCAACGTAATGTTGGCATATG\
AGTTATGGCGCCTGGAGGGGAGATAGAAAGGTGTAGCGTTAATACTAGCTAGAAGAAAGT\
AAAACAGTCGAACTCAAGAGAAAGAACTGGGTGCGTGATTGTTATTAAGAGCGAGACTCT\
ATAGGCCGTACGCTCCTACATACTTGCAACTCGGGTGGTTGGTACCAGTCGTCCTAAAGC\
GATTACTCCCAAGTGCTTGCATGTCCTATGGATTCACCTATAGCGTCGGTTTAGATTAAT\
AAATTGGTTTATGTAATACTCAATTCTCACGTGCACGCGTACATGAAGTGCGCTTATCGG\
GACTGCGTTGTCTATGGCTCGGGTGGGGCGGCCGGTGTGTCTGGTATTTGGGCGCAAAAG\
GCCTGTCCACGGGCTATTTGGTAGGCTCGTTATAGCTTGCAAACTCAAACACGGACCCGT\
CAGTAGTACAGAACCCCTTTCTTTAGCTTCAATTGTGAGCAACAGCCGGCAGAGTCGTTA\
GGTGCTCGGGAGCAGACTAGCAACAAATTGGTCTAATACTCACACGATTTAGATACACGA\
GAAGGCGTGCTCACGAGAAGAAAGGTACCCAGGTCCGATCTGATTCTAATCACAGTGATC\
TTGGATTTGCCCTTTGTAGGTACACTCATTAACAAAATGACCAAGTGATAGCGCCGTCTT\
TCTCAAATACGGCTGCCTGAATAGGTGACCACATTGGTTAATAAGTCCAAGTCCATAAGT\
AGGTCGCGTGATGTGTAGCTAGTCTGGTAGCGCAGTCACTGTTGCGCGACACAGATAGTA\
AGATAACGCCGCCGACCCCTAGAGTCAATACGGCTTACATGGGGATCTATTACAGTCGAC\
TATGGTGTGGTCGGCTGCAGGAGTACGGCCTAGGAGACACGGGCAAACTTCGTCAGACTT\
AAACTGCAGGCGGCGCCGACATTAGAGTTACCTCGTAGTGAATCACCTTTCGCCAGCCTC\
CGCCCTGTCTATGCCTTTGGAAGTGTATCTATTGGGGACATTCTTCCTTCGAGTCGAGGC\
GACTCCTTCGTGGGACTTCCTCACGTTTTGCTACCAATTGGTCGGTACAGCCAACTAAAG\
AGACACTAGTTTCTGATGTATAGATACAGGCGTCAGGGCTAGCTGTAGGAAATCGCACTA\
TCGGTCCACTGGCGGCAACGATATAGTCAAAATTAAGGCTGCGGAGATACTACGGGCTGC\
AAGTATAAGCCAAAGTACTGGAACGCTCTACTCCTCGGTCACAAGCTCTATTCGGAGAGG\
TGTTCTGTAACGTTCGATGGGGCCCCTCTGGATTAAGGAACTTCTAATCCCGTGACCTGA\
CGGATGAGACACAAGGTCTCGTTGATCATACTCCCGAACCCGACGAATGACACCCATCCG\
TATGGCGGGGCGGCGCAACGAGTCCCTGGACGTAAATCCAGACATCACCTGCATCTAGAG\
AATCCGATTATCCCGAATGCACGATTGAAACTCGACTCAAAACTTTATTAAATATGAGCA\
TATAATGTCCTTCTGGGCGTCAACACCAATTCGGATTACGCACAGCGGCTTTCAATACCA\
TGCCCGTCCGCGGAGCGGCCGCAATGCATAAACTACCCTGTGTATACAACTCCAACATCA\
TGTTCTGGTAGGGTCGCTCTACACTTGCGCGGGAGTAGCACACAGGGTCCAGCCCGTTCC\
GTGTAGTTTCTTTCAGTCGCCGCCGCCTCTGGCGG"


    dist = EditDistance(S, T)
    print dist

if __name__ == '__main__':
    main()